--- 
services: 
    redis: 
        image: bitnami/redis
        restart: always
        networks:
            - meisterwerk
    api: 
        depends_on: 
        - redis
        networks:
            - meisterwerk
    websites: 
        restart: always
        networks:
            - meisterwerk
version: "3"
networks:
    meisterwerk:
    